select * from dbo.sales_data

-- Show me sales of country and region 
select country,territory,format(round(sum(sales),2),'c') as Country_Sales 
from dbo.sales_data
where country is not null
group by country,territory

-- What about sales per country per year? 

select country,
datepart(year,orderdate) as year, 
format(round(sum(sales),2),'c') as Country_SalesbyYear
from dbo.sales_data
where country is not null 
group by country,datepart(year,orderdate)
order by 1,2

--Show me sales per region per year

select 
territory,
datepart(year,orderdate) as year, 
format(round(sum(sales),2),'c') as Region_SalesbyYear
from dbo.sales_data
where TERRITORY is not null 
group by territory,datepart(year,orderdate)
order by 1,2

-- Show me count of orders per year
select 
count(ordernumber) as total_orders,
datepart(year,orderdate) as year
from dbo.sales_data
group by datepart(year,orderdate)
order by 2

-- show me count of orders per quarter 
select 
count(ordernumber) as total_orders,
datepart(year,orderdate) as year,
qtr_id as quarter
from dbo.sales_data
group by datepart(year,orderdate),qtr_id
order by 2,3

-- show me a running total of sales for all years 
with salestotal as (select 
datepart(year,orderdate) as year,
datepart(month,orderdate) as month,
round(sum(sales),2) as sales  
from dbo.sales_data
group by datepart(year,orderdate),
datepart(month,orderdate) 
)
select 
year,
month,
sales,
sum(sales) over (partition by year order by year, month rows between unbounded preceding and current row ) as running_total
from salestotal
order by year,month 

-- Show me year over year dollar delta and percent change 

with yearlysales as (select 
datepart(year,orderdate) as year,
round(sum(sales),2) as sales
from dbo.sales_data
group by datepart(year,orderdate)
)
select 
year,
sales,
COALESCE(lag(sales) over (order by year asc ),0) as previous_year_sales,
COALESCE(sales - lag(sales) over (order by year asc ),0) as dollar_difference,
COALESCE((SALES - lag(sales) over (order by year asc )) / sales * 100,0) as percent_difference 
from yearlysales

-- Show me sales by product 

select 
datepart(year,orderdate) as year,
productline,
round(sum(sales),2) as sales 
from dbo.sales_data
group by datepart(year,orderdate), productline
order by 1,2

-- show me rank of sales by product line 

select 
datepart(year,orderdate) as year,
productline,
sum(sales),
rank() over (partition by datepart(year,orderdate) order by sum(sales) desc ) as rank
from dbo.sales_data
group by datepart(year,orderdate),productline

-- show the number one productline by sales for each year
with ranking as (
select 
datepart(year,orderdate) as year,
productline,
sum(sales) as total_sales,
rank() over (partition by datepart(year,orderdate) order by sum(sales) desc ) as rank
from dbo.sales_data
group by datepart(year,orderdate),productline
)
select 
year,
productline,
format(round(total_sales,2),'c') Total_dollar_sales
from ranking
where rank = 1 

-- What country made the most orders in 2003? 
select 
datepart(year,orderdate) as 'year',
country,
count(ordernumber) as total_orders,
round(sum(sales),2) as total_sales 
from dbo.sales_data
where datepart(year,orderdate) = '2003'
group by datepart(year,orderdate),country
order by 3 desc,4 desc 

--- What customers and region made  orders in 2003?
select 
customername, 
count(case when territory = 'EMEA' then ordernumber end) as EMEA_Order_count,
count(case when territory = 'NA' then ordernumber end) as NA_Order_count,
count(case when territory = 'APAC' then ordernumber end) as APAC_Order_count
from dbo.sales_data
where datepart(year,orderdate) = '2003'
group by customername

-- what customer made the biggest order in 2003?
select 
customername,city,sales
from dbo.sales_data
where SALES in (select max(sales) from dbo.sales_data where datepart(year,orderdate) = '2003')

-- what customers made larger than average orders in 2003? 
select 
customername,city,format(round(sales,2),'c')
from dbo.sales_data
where sales > (select avg(sales) from dbo.sales_data where datepart(year,orderdate) = '2003')

-- For all country, find percentage of revenue generated by orders in 2003
with total_sales as (select 
sum(sales) as yearsales
from dbo.sales_data
where DATEPART(year,orderdate) = '2003' 
)
select 
sd.country,
sum(sd.sales) as revenue ,
round(sum(sd.sales) / ts.yearsales *100,2) as revenue_percentage
from total_sales ts,dbo.sales_data sd
where DATEPART(year,ORDERDATE) = '2003'
group by sd.country,ts.yearsales

--What is the average price per order? 
with order_total_price as (select 
ORDERNUMBER,
sum(sales) as total_price
from dbo.sales_data
group by ORDERNUMBER
)
select avg(total_price) as avg_total_price
from order_total_price

--What was the avg quantity of items per order 

with total_items as (select 
ORDERNUMBER,
SUM(QUANTITYORDERED) as items_ordered
from dbo.sales_data
group by ORDERNUMBER
)
select avg(items_ordered)
from total_items 

 --What State had the most sales? 
 select 
 DATEPART(year,ORDERDATE) as year,
 STATE,
 sum(sales)
 FROM DBO.sales_data
 WHERE COUNTRY = 'USA'
 GROUP BY DATEPART(year,ORDERDATE),STATE
 ORDER BY year,3 desc

--- Rank the states by sales 
 select 
 DATEPART(year,ORDERDATE) as year,
 STATE,
 sum(sales),
 rank() over ( partition by DATEPART(year,ORDERDATE) order by sum(sales) desc ) as rank 
 FROM DBO.sales_data
 WHERE COUNTRY = 'USA'
 GROUP BY DATEPART(year,ORDERDATE),STATE
 ORDER BY year,3 desc

---Count Dealsize by state 
select 
 DATEPART(year,ORDERDATE) as year,
 STATE,
 Count(case when DEALSIZE = 'Small' THEN ORDERNUMBER END ) as 'Small Orders',
 count(case when DEALSIZE = 'Medium' THEN ORDERNUMBER END) AS 'Medium Orders',
 Count(case when DEALSIZE = 'Large' then ORDERNUMBER END) AS 'Large Orders'
 from dbo.sales_data
 WHERE COUNTRY = 'USA'
 group  by DATEPART(year,ORDERDATE),STATE
 ORDER BY 1




